sudo: required
services:
  - docker

before_install:
  - docker build -t giadat1599/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run giadat1599/react-test npm run test

after_success:
  - docker build -t giadat1599/multi_client ./client
  - docker build -t giadat1599/multi_nginx ./nginx
  - docker build -t giadat1599/multi_server ./server
  - docker build -t giadat1599/multi_worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push giadat1599/multi_client
  - docker push giadat1599/multi_nginx
  - docker push giadat1599/multi_server
  - docker push giadat1599/multi_worker
# deploy:
#   provider: elasticbeanstalk
#   region: 'ap-northeast-1'
#   app: 'multi-docker'
#   env: 'Multidocker-env'
#   bucket_name: 'elasticbeanstalk-ap-northeast-1-760038101556'
#   bucket_path: 'multi-docker'
#   on:
#     branch: main
#   access_key_id: '$AWS_ACCESS_KEY'
#   secret_access_key: '$AWS_SECRET_KEY'
