version: '3'
services:
  client:
    image: giadat1599/multi_client
    mem_limit: 128m
    hostname: client
  server:
    image: giadat1599/multi_server
    mem_limit: 128m
    hostname: api
    environment:
      REDIS_HOST: $REDIS_HOST
      REDIS_PORT: $REDIS_PORT
      PG_USER: $PGUSER
      PG_PASSWORD: $PGPASSWORD
      PG_HOST: $PGHOST
      PG_PORT: $PGPORT
      PG_DATABASE: $PGDATABASE
  worker:
    image: giadat1599/multi_worker
    mem_limit: 128m
    hostname: worker
    environment:
      REDIS_HOST: $REDIS_HOST
      REDIS_PORT: $REDIS_PORT
  nginx:
    image: giadat1599/multi_nginx
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"