version: '3'
services:
  postgres:
    image: postgres:latest
    environment:    
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
  redis:
    image: redis:latest
  nginx:
    restart: always
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "3050:80"
    depends_on:
      - client
      - api
  api:
    build: 
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PG_USER: postgres
      PG_PASSWORD: postgres_password
      PG_HOST: postgres
      PG_PORT: 5432
      PG_DATABASE: postgres
    depends_on:
      - postgres
      - redis
  worker:
    build: 
      context: ./worker
      dockerfile: Dockerfile    
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile 
    volumes:
      - /app/node_modules
      - ./client:/app

